INSERT INTO PAIS (NOME,CODIGO_ISO) VALUES ('Brasil','BR');
INSERT INTO PAIS (NOME,CODIGO_ISO) VALUES ('Argentina','AR');

SELECT * FROM PAIS;


INSERT INTO ESTADO (NOME,SIGLA,PAIS_ID) VALUES ('São Paulo','SP',1);
INSERT INTO ESTADO (NOME,SIGLA,PAIS_ID) VALUES ('Rio de Janeiro','RJ',1);
INSERT INTO ESTADO (NOME,SIGLA,PAIS_ID) VALUES ('Minas Gerais','MG',1);
INSERT INTO ESTADO (NOME,SIGLA,PAIS_ID) VALUES ('Paraná','PR',1);
INSERT INTO ESTADO (NOME,SIGLA,PAIS_ID) VALUES ('Santa Catarina','SC',1);

SELECT * FROM ESTADO;


INSERT INTO CIDADE (NOME,LATITUDE,LONGITUDE,ESTADO_ID)
VALUES ('Osasco',-23.532900,-46.791600,1);

INSERT INTO CIDADE
VALUES(DEFAULT,'São Paulo',-23.550500,-46.633300,1);

INSERT INTO CIDADE
VALUES(DEFAULT,'Santos',-23.960800,-46.333600,1);

INSERT INTO CIDADE
VALUES(DEFAULT,'Campinas',-22.909900,-47.062600,1);

INSERT INTO CIDADE
VALUES(DEFAULT,'Petropolis',-22.505000,-43.178900,2);

INSERT INTO CIDADE
VALUES(DEFAULT,'Niteroi',-22.883200,-43.103400,2);

INSERT INTO CIDADE
VALUES(DEFAULT,'Belo Horizonte',-19.916700,-43.934500,3);

INSERT INTO CIDADE
VALUES(DEFAULT,'Blumenau',-26.919400,-49.066100,5);

SELECT * FROM CIDADE;


INSERT INTO BAIRRO VALUES(DEFAULT,'Centro',220000,12.4,1);
INSERT INTO BAIRRO VALUES(DEFAULT,'Presidente Altino',45000,4.3,1);
INSERT INTO BAIRRO VALUES(DEFAULT,'Jaguaribe',62000,8.1,1);
INSERT INTO BAIRRO VALUES(DEFAULT,'Mooca',75000,7.4,2);
INSERT INTO BAIRRO VALUES(DEFAULT,'Vila Leopoldina',39000,6.1,2);
INSERT INTO BAIRRO VALUES(DEFAULT,'Ponta da Praia',28000,3.9,3);
INSERT INTO BAIRRO VALUES(DEFAULT,'Taquaral',41000,5.8,4);
INSERT INTO BAIRRO VALUES(DEFAULT,'Centro Histórico',30000,4.7,5);
INSERT INTO BAIRRO VALUES(DEFAULT,'Pampulha',58000,10.3,7);
INSERT INTO BAIRRO VALUES(DEFAULT,'Velha',52000,9.8,8);

SELECT * FROM BAIRRO;


INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Margem Rio Tietê Osasco',
-23.531200,
-46.791100,
760,
14,
12,
82,
350,
'Argiloso',
'Alto',
'S',
1
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Córrego Bussocaba',
-23.553400,
-46.767200,
748,
11,
18,
70,
180,
'Argiloso',
'Medio',
'S',
2
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Rio Jaguaribe',
-23.544900,
-46.784300,
740,
18,
9,
75,
120,
'Argiloso',
'Alto',
'S',
3
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Marginal Tiete',
-23.527500,
-46.660200,
730,
5,
8,
95,
70,
'Arenoso',
'Muito Alto',
'S',
4
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Leopoldina Norte',
-23.525700,
-46.732100,
728,
7,
20,
91,
150,
'Argiloso',
'Muito Alto',
'S',
5
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Canal Santos',
-23.971200,
-46.318700,
5,
2,
15,
98,
20,
'Arenoso',
'Muito Alto',
'S',
6
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Lagoa Taquaral',
-22.889300,
-47.065100,
680,
6,
24,
45,
900,
'Misto',
'Medio',
'S',
7
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Centro Petropolis',
-22.509600,
-43.177100,
845,
24,
40,
40,
500,
'Rochoso',
'Baixo',
'S',
8
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Pampulha Norte',
-19.858300,
-43.971200,
860,
4,
18,
55,
430,
'Argiloso',
'Medio',
'S',
9
);

INSERT INTO REGIAO_MONITORADA
VALUES(
DEFAULT,
'Vale Blumenau',
-26.915100,
-49.071500,
30,
21,
65,
35,
200,
'Argiloso',
'Baixo',
'S',
10
);

SELECT * FROM REGIAO_MONITORADA;


INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Chuva Tietê','PLUVIOMETRO','mm','ATIVO',DEFAULT,1);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Nivel Tietê','NIVEL_AGUA','cm','ATIVO',DEFAULT,1);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Solo Bussocaba','UMIDADE_SOLO','%','ATIVO',DEFAULT,2);
INSERT INTO SENSOR VALUES(DEFAULT,'Pluviometro Jaguaribe','PLUVIOMETRO','mm','ATIVO',DEFAULT,3);
INSERT INTO SENSOR VALUES(DEFAULT,'Nivel Marginal','NIVEL_AGUA','cm','ATIVO',DEFAULT,4);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Leopoldina','PLUVIOMETRO','mm','ATIVO',DEFAULT,5);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Santos','NIVEL_AGUA','cm','ATIVO',DEFAULT,6);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Taquaral','PLUVIOMETRO','mm','ATIVO',DEFAULT,7);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Petrópolis','PLUVIOMETRO','mm','ATIVO',DEFAULT,8);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Pampulha','NIVEL_AGUA','cm','ATIVO',DEFAULT,9);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Blumenau','PLUVIOMETRO','mm','ATIVO',DEFAULT,10);
INSERT INTO SENSOR VALUES(DEFAULT,'Sensor Reserva','UMIDADE_SOLO','%','ATIVO',DEFAULT,1);

SELECT * FROM SENSOR;


INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (92,1);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (178,2);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (81,3);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (105,4);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (220,5);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (88,6);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (145,7);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (63,8);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (131,9);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (176,10);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (44,11);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (71,12);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (84,1);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (190,2);
INSERT INTO LEITURA_SENSOR (VALOR,SENSOR_ID) VALUES (77,3);

SELECT * FROM LEITURA_SENSOR;


INSERT INTO LEITURA_CLIMA
(PRECIPITACAO_MM,TEMPERATURA_C,UMIDADE_PERCENTUAL,PRESSAO_HPA,VENTO_KMH,SATURACAO_SOLO_PERCENTUAL,REGIAO_MONITORADA_ID)
VALUES(110,24,95,1004,16,88,1);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,95,25,88,1002,10,90,2);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,120,23,91,1001,20,93,3);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,65,27,78,1009,15,66,4);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,130,22,96,1000,11,95,5);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,150,21,98,998,12,97,6);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,82,24,81,1005,14,73,7);
INSERT INTO LEITURA_CLIMA VALUES(DEFAULT,DEFAULT,74,25,80,1008,13,62,8);

SELECT * FROM LEITURA_CLIMA;


INSERT INTO HISTORICO_EVENTO
(TIPO_EVENTO,PRECIPITACAO_MM,ALTURA_AGUA_CM,DURACAO_HORAS,SEVERIDADE,REGIAO_MONITORADA_ID)

VALUES
('ENCHENTE',120,180,8,'ALTA',1);

INSERT INTO HISTORICO_EVENTO
VALUES(
DEFAULT,
DEFAULT,
'ALAGAMENTO',
90,
120,
5,
'MEDIA',
3
);

INSERT INTO HISTORICO_EVENTO
VALUES(
DEFAULT,
DEFAULT,
'ENCHENTE',
150,
220,
10,
'ALTA',
5
);

INSERT INTO HISTORICO_EVENTO
VALUES(
DEFAULT,
DEFAULT,
'DESLIZAMENTO',
140,
35,
12,
'ALTA',
8
);

INSERT INTO HISTORICO_EVENTO
VALUES(
DEFAULT,
DEFAULT,
'ALAGAMENTO',
80,
95,
3,
'BAIXA',
7
);

SELECT * FROM HISTORICO_EVENTO;


INSERT INTO SCORE_RISCO
(SCORE,PESO_CLIMA,PESO_GEOGRAFIA,PESO_URBANIZACAO,PESO_HISTORICO,JUSTIFICATIVA,REGIAO_MONITORADA_ID)
VALUES
(92,30,20,25,25,'Alta impermeabilizacao e chuva intensa',1);
INSERT INTO SCORE_RISCO VALUES(DEFAULT,DEFAULT,85,28,20,20,17,'Histórico recorrente',3);
INSERT INTO SCORE_RISCO VALUES(DEFAULT,DEFAULT,97,35,22,20,20,'Região crítica',5);
INSERT INTO SCORE_RISCO VALUES(DEFAULT,DEFAULT,70,22,18,16,14,'Risco moderado',7);
INSERT INTO SCORE_RISCO VALUES(DEFAULT,DEFAULT,88,30,20,20,18,'Solo saturado',8);

SELECT * FROM SCORE_RISCO;


INSERT INTO ALERTA
(NIVEL,MENSAGEM,REGIAO_MONITORADA_ID,SCORE_RISCO_ID)
VALUES
('CRITICO','Possibilidade elevada de enchente',1,1);
INSERT INTO ALERTA VALUES(DEFAULT,DEFAULT,'ALTO','Monitoramento intensificado','S',3,2);
INSERT INTO ALERTA VALUES(DEFAULT,DEFAULT,'CRITICO','Evacuacao recomendada','S',5,3);
INSERT INTO ALERTA VALUES(DEFAULT,DEFAULT,'MEDIO','Acompanhar previsao','S',7,4);
INSERT INTO ALERTA VALUES(DEFAULT,DEFAULT,'ALTO','Solo extremamente saturado','S',8,5);

SELECT * FROM ALERTA;


INSERT INTO APP_USER(NOME,EMAIL,SENHA,TIPO_USUARIO) VALUES('Administrador Sistema','admin@sosenchentes.com','123','ADMIN');
INSERT INTO APP_USER(NOME,EMAIL,SENHA,TIPO_USUARIO) VALUES('Operador Monitoramento','operador@sosenchentes.com','123','OPERADOR');
INSERT INTO APP_USER(NOME,EMAIL,SENHA,TIPO_USUARIO) VALUES('Defesa Civil','defesa@sosenchentes.com','123','GESTOR');

SELECT * FROM APP_USER;
